Repository thoth-station/metrics-exporter, pull requests merged in 2019-06, with the labels that each got.

#41 Automatic update of dependency uvicorn from 0.7.1 to 0.7.2
  Pipfile.lock
Labels: bot

#42 Automatic update of dependency thoth-storages from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#43 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#44 Automatic update of dependency prometheus-client from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#15 fixed webhhok url
  .zuul.yaml
Labels: approved, size/S, size/XS

#47 Automatic update of dependency uvicorn from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: bot

#48 Automatic update of dependency uvicorn from 0.7.3 to 0.8.0
  Pipfile.lock
Labels: bot

#49 Automatic update of dependency uvicorn from 0.8.0 to 0.8.1
  Pipfile.lock
Labels: bot

#46 Add generic trigger to buildconfig template
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#50 Feature/configmaps metrics
  app.py
  openshift/deployment-template.yaml
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs.py
Labels: approved, size/L, size/M

#51 Explicitly set all namespaces
  openshift/deployment-template.yaml
  thoth/metrics_exporter/jobs.py
Labels: approved, size/M

#52 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#53 Correct duplicate
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#54 Automatic update of dependency prometheus-client from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#55 Debug off
  app.py
Labels: approved, size/XS

#56 Changed inizialization of jobs
  thoth/metrics_exporter/jobs.py
Labels: approved, size/S, size/XS

#57 Increase resources for metrics-exporter
  openshift/deployment-template.yaml
Labels: approved, size/XS

#58 Provide readiness and liveness probes
  openshift/deployment-template.yaml
Labels: approved, size/S

#61 Automatic update of dependency uvicorn from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#60 Rewrite metrics exporter to gunicorn+flask
  Pipfile
  Pipfile.lock
  app.py
  openshift/deployment-template.yaml
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
  wsgi.py
Labels: approved, size/XL

#62 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot

#63 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#59 Added two new job status
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#65 Automatic update of dependency thoth-storages from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#67 Corrected status and logic to identify the failure due to BackOffLimi…
  thoth/metrics_exporter/jobs.py
Labels: approved, size/S

#70 Add new status
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS
