Repository thoth-station/metrics-exporter, pull requests merged in 2019-09, with the labels that each got.

#112 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#114 Switch from Dgraph to PostgreSQL in deployment
  openshift/deployment-template.yaml
Labels: approved, size/M

#95 Generalized metrics for Jobs
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L, size/M

#115 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#116 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#119 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: approved, size/XS

#120 Drop total_instances_per_node metrics with transition to a relational db
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#121 Disable graph cache completely in deployment
  openshift/deployment-template.yaml
Labels: approved, size/XS

#118 Do not count total nodes with recent transition to relational db
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#122 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#123 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#124 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#125 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#126 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#127 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#128 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#129 Simplify metrics error handling for graphdb and ceph connection errors
  thoth/metrics_exporter/jobs.py
Labels: approved, size/L

#130 Add job label to monitor solver jobs
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#132 use postgresql hostname from thoth configmap
  openshift/deployment-template.yaml
Labels: approved, size/XS

#133 Fix listing of functions for registered jobs
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#134 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#135 New labels to monitor package analyzer and package extract
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#136 Metrics for provenance-chcker and adviser
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#137 All jobs and configmaps standardized
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#139 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#140 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot
