Repository thoth-station/metrics-exporter, pull requests merged in 2019-10, with the labels that each got.

#141 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#143 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#144 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#149 Print Metrics Exporter version on startup
  wsgi.py
Labels: approved, do-not-merge/needs-rebase, size/XS

#138 Introduce metrics classes, update and create metrics
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
  wsgi.py
Labels: approved, size/L, size/XL

#150 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#152 Correct import class name
  wsgi.py
Labels: approved, do-not-merge/needs-rebase, size/XS

#156 Simplify registering a job
  thoth/metrics_exporter/jobs.py
  wsgi.py
Labels: approved, size/L

#158 Use decorator package to correctly decorate classmethods
  Pipfile
  Pipfile.lock
  thoth/metrics_exporter/jobs.py
Labels: approved, size/L

#159 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#160 Make Grafana URL redirection configurable
  openshift/deployment-template.yaml
  wsgi.py
Labels: approved, size/XS

#163 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#161 Remove unused debug variable
  wsgi.py
Labels: approved, size/XS

#164 Automatic update of dependency decorator from 4.4.0 to 4.4.1
  Pipfile.lock
Labels: bot

#165 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#162 Properly handle jobs registration and split jobs per files
  .coafile
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/base.py
  thoth/metrics_exporter/jobs/ceph.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/openshift.py
  thoth/metrics_exporter/jobs/package_analyzer.py
  thoth/metrics_exporter/jobs/pi.py
  thoth/metrics_exporter/jobs/python.py
  thoth/metrics_exporter/jobs/software_environment.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
  thoth/metrics_exporter/metrics.py
  wsgi.py
Labels: approved, size/XXL

#166 Capture exception if database schema is not initialized yet
  thoth/metrics_exporter/jobs/db.py
Labels: approved, size/XS

#168 Fix import statement
  thoth/metrics_exporter/jobs/db.py
Labels: approved, size/XS

#170 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#169 Update queries according to new naming convention
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/pi.py
  thoth/metrics_exporter/jobs/python.py
  thoth/metrics_exporter/jobs/software_environment.py
  thoth/metrics_exporter/jobs/user.py
Labels: approved, size/M

#171 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
