Repository thoth-station/metrics-exporter, pull requests merged in 2019-04, with the labels that each got.

#16 Automatic update of dependency uvicorn from 0.7.0b1 to 0.7.0b2
  Pipfile.lock
Labels: bot

#17 Automatic update of dependency thoth-common from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#18 Automatic update of dependency thoth-common from 0.8.2 to 0.8.3
  Pipfile.lock
Labels: bot

#19 Automatic update of dependency thoth-common from 0.8.3 to 0.8.4
  Pipfile.lock
Labels: bot

#20 Automatic update of dependency thoth-common from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#21 New metrics to observe the content of Thoth Graph database
  app.py
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs.py
Labels: approved, size/L

#24 Automatic update of dependency thoth-storages from 0.9.7 to 0.10.0
  Pipfile.lock
Labels: bot

#25 Automatic update of dependency uvicorn from 0.7.0b2 to 0.7.0
  Pipfile.lock
Labels: bot

#26 Fix typo in argument and variable name
  thoth/metrics_exporter/jobs.py
Labels: approved, size/S

#27 Automatic update of dependency thoth-storages from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot
