Repository thoth-station/metrics-exporter, pull requests merged in 2019-03, with the labels that each got.

#11 Use standardized Python package name to fix issues in Kebechet
  Pipfile
  Pipfile.lock
Labels: size/XL

#12 Use OpenShift to gather service account token on local run
  thoth/metrics_exporter/jobs.py
Labels: size/XS

#10 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#14 Automatic update of dependency uvicorn from 0.6.1 to 0.7.0b1
  Pipfile.lock
Labels: bot

#13 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot
