Repository thoth-station/metrics-exporter, pull requests merged in 2019-12, with the labels that each got.

#233 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#234 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/M

#235 Automatic update of dependency sentry-sdk from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/S

#237 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/S

#238 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/S

#241 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#247 Make coala happy again
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/M

#246 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: approved, bot, size/M

#244 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#245 New query for Python Packages
  Pipfile
  Pipfile.lock
  openshift/deployment-template.yaml
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#248 Fix api version in templates
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#250 Make namespace and prometheus token mandatory
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#252 Correct variable
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#254 Change metric order
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/M

#255 Introduce safe check
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/S

#256 Adjust time initialization of the metric
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/S

#257 Adjust Counter
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S
