Repository thoth-station/metrics-exporter, pull requests merged in 2019-11, with the labels that each got.

#175 Created metrics to avoid 'race conditions'
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#176 Use enums in queries to the database
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
Labels: approved, size/S, size/XS

#177 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#178 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#179 Update function
  thoth/metrics_exporter/jobs/python.py
Labels: approved, size/XS

#182 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#183 Automatic update of dependency gunicorn from 19.9.0 to 20.0.0
  Pipfile.lock
Labels: bot

#184 added CORS headers and allow from all
  Pipfile
  Pipfile.lock
  wsgi.py
Labels: enhancement

#186 Enable coalescing in jobs executed
  wsgi.py
Labels: approved

#187 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#188 Document scheduler endpoints
  README.md
Labels: approved, size/S

#189 Add job defaults configuration
  wsgi.py
Labels: approved, size/XS

#191 Explictly set misfire grace time to a high value
  wsgi.py
Labels: approved, size/XS

#192 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#193 Optimize queries for jobs and configmaps
  thoth/metrics_exporter/jobs/openshift.py
Labels: approved, size/M

#194 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#190 Less than and greater than signs need to be escaped
  README.md
Labels: approved, size/S

#197 Give metrics-exporter more time to boot
  openshift/deployment-template.yaml
Labels: approved, size/XS

#198 Log if service is not ready yet on start up
  wsgi.py
Labels: approved, size/XS

#196 Adjust metrics to report 0 if no frameworks from inspections found in the database
  thoth/metrics_exporter/jobs/pi.py
Labels: approved, size/S

#200 Increase initial delay seconds even more to make sure the service is up
  openshift/deployment-template.yaml
Labels: approved, size/XS

#201 Notify about readiness in logs
  wsgi.py
Labels: approved, size/XS

#202 Fix typo in the comment
  wsgi.py
Labels: approved, size/XS

#199 Maintain a signle graph database instance per metrics-exporter
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/base.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/openshift.py
  thoth/metrics_exporter/jobs/package_analyzer.py
  thoth/metrics_exporter/jobs/pi.py
  thoth/metrics_exporter/jobs/python.py
  thoth/metrics_exporter/jobs/software_environment.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
Labels: do-not-merge/needs-rebase, size/L

#203 Increment metrics evaluation counter each time a metrics method is called
  wsgi.py
Labels: approved, size/S

#204 Measure metrics job execution and print them to logs
  thoth/metrics_exporter/jobs/base.py
Labels: approved, size/XS

#205 WIP: Try thread pool executor with 16 threads
  wsgi.py
Labels: approved, do-not-merge/work-in-progress, size/XS

#208 Use own threadpool for gathering metrics
  Pipfile
  Pipfile.lock
  README.md
  openshift/deployment-template.yaml
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/base.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/openshift.py
  thoth/metrics_exporter/jobs/package_analyzer.py
  thoth/metrics_exporter/jobs/pi.py
  thoth/metrics_exporter/jobs/python.py
  thoth/metrics_exporter/jobs/software_environment.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
  thoth/metrics_exporter/metrics.py
  wsgi.py
Labels: approved, size/L

#210 Fix logging error produced when showing results
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#211 Remove duplicate information from logs
  thoth/metrics_exporter/jobs/base.py
Labels: approved, size/XS

#213 Add sentry-sdk[flask] and aiocontextvars for Sentry integrations
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#212 Print warning to log if a metrics gathering job was missed
  wsgi.py
Labels: approved, size/S

#214 Print thread id to check running thread workers
  wsgi.py
Labels: approved, size/XS

#215 Print missing metrics to log if they were not computed
  wsgi.py
Labels: approved, size/XS

#216 Iterate over items, fix issue
  wsgi.py
Labels: approved, size/XS

#217 Log exception in thread pool worker
  wsgi.py
Labels: approved, size/XS

#218 Introduce weak readiness configuration
  openshift/deployment-template.yaml
  wsgi.py
Labels: approved, size/XS

#219 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#220 Automatic update of dependency gunicorn from 20.0.0 to 20.0.2
  Pipfile.lock
Labels: bot, size/XS

#221 Automatic update of dependency sentry-sdk from 0.13.2 to 0.13.3
  Pipfile.lock
Labels: bot, size/XS

#222 Do not re-raise exception from thread worker
  wsgi.py
Labels: approved, size/S

#224 Automatic update of dependency gunicorn from 20.0.2 to 20.0.3
  Pipfile.lock
Labels: bot, size/M

#225 Automatic update of dependency sentry-sdk from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot

#226 Automatic update of dependency gunicorn from 20.0.3 to 20.0.4
  Pipfile.lock
Labels: bot, size/XS

#227 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#229 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/M

#230 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M
