Repository thoth-station/metrics-exporter, pull requests merged in 2019-07, with the labels that each got.

#71 New environments variables to monitor AMUN namespaces
  openshift/deployment-template.yaml
  thoth/metrics_exporter/jobs.py
Labels: approved, size/S

#72 Increment only failed for failed jobs which will not retry
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#73 Monitor also component labels in configmaps
  thoth/metrics_exporter/jobs.py
Labels: approved, size/S

#74 Automatic update of dependency thoth-storages from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot

#75 Automatic update of dependency thoth-storages from 0.14.4 to 0.14.5
  Pipfile.lock
Labels: bot

#76 Automatic update of dependency thoth-storages from 0.14.5 to 0.14.6
  Pipfile.lock
Labels: bot

#77 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#78 Automatic update of dependency thoth-storages from 0.14.6 to 0.14.7
  Pipfile.lock
Labels: bot

#79 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#81 Automatic update of dependency thoth-storages from 0.14.7 to 0.14.8
  Pipfile.lock
Labels: bot

#82 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#83 Automatic update of dependency thoth-storages from 0.14.8 to 0.15.0
  Pipfile.lock
Labels: bot

#85 Automatic update of dependency thoth-storages from 0.15.0 to 0.15.1
  Pipfile.lock
Labels: bot

#86 Automatic update of dependency thoth-storages from 0.15.1 to 0.15.2
  Pipfile.lock
Labels: bot

#87 changed sa from thoth-ops to metrics-exporter
  openshift/deployment-template.yaml
Labels: approved, size/XS

#88 Automatic update of dependency thoth-common from 0.9.4 to 0.9.5
  Pipfile.lock
Labels: bot

#90 Automatic update of dependency thoth-storages from 0.15.2 to 0.16.0
  Pipfile.lock
Labels: bot

#89 Created metrics to monitor Ceph results
  openshift/deployment-template.yaml
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#93 Automatic update of dependency thoth-storages from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot

#92 Added metrics to check inspections in Ceph per identifier (if any)
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#91 Added PackageAnalysisResultStore
  thoth/metrics_exporter/jobs.py
Labels: approved, size/XS

#94 Created metrics for PI
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M, size/S

#96 Automatic update of dependency thoth-storages from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: bot
