Repository thoth-station/metrics-exporter, pull requests merged in 2019-08, with the labels that each got.

#97 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#98 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#99 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#100 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#101 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#102 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#103 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/XL

#104 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#105 Introduce metrics for unsolved Python packages count
  thoth/metrics_exporter/jobs.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#107 Provide infra namespace to list installed solvers
  openshift/deployment-template.yaml
Labels: approved, size/XS

#108 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#109 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#110 Added config
  .thoth.yaml
Labels: approved, size/S
