Repository thoth-station/metrics-exporter, pull requests merged in 2019-05, with the labels that each got.

#28 Automatic update of dependency uvicorn from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#30 Automatic update of dependency thoth-storages from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: bot

#29 Modified metrics for Dgraph
  Pipfile
  app.py
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs.py
Labels: approved, size/L

#31 Configure Dgraph in deployment
  openshift/deployment-template.yaml
Labels: approved, size/S

#32 Update functions for new schema and add new metrics
  app.py
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs.py
Labels: approved

#33 Created service metrics for graph-sync jobs for all categories
  app.py
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs.py
Labels: approved

#35 updated pipfile-lock
  Pipfile.lock
Labels: approved, size/L

#36 Automatic update of dependency thoth-storages from 0.11.4 to 0.14.0
  Pipfile.lock
Labels: bot

#37 Modify connection error exception metrics to activate Prometheus alerts
  thoth/metrics_exporter/jobs.py
Labels: approved, size/S

#38 Corrected metrics to set the connection error to 0
  thoth/metrics_exporter/jobs.py
Labels: approved, size/M, size/S

#34 added namespace to deployment trigger
  openshift/deployment-template.yaml
Labels: approved, size/XS
