Repository thoth-station/metrics-exporter, pull requests merged in 2020-03, with the labels that each got.

#339 Increase time for successful adviser
  thoth/metrics_exporter/metrics.py
Labels: approved, size/XS

#340 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/M

#342 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot, size/L

#343 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.4
  Pipfile.lock
Labels: bot, size/S

#344 Automatic update of dependency thoth-storages from 0.22.4 to 0.22.5
  Pipfile.lock
Labels: bot, size/XS

#345 Automatic update of dependency sentry-sdk from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#346 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot, size/M

#347 Automatic update of dependency thoth-common from 0.12.0 to 0.12.3
  Pipfile.lock
Labels: bot, size/M

#348 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/S

#349 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/S

#350 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/M
