Repository thoth-station/metrics-exporter, pull requests merged in 2020-06, with the labels that each got.

#402 Release of version 0.8.3
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: bot, size/M

#399 Introduce kebechet metrics, some refactoring and update README
  README.md
  thoth/metrics_exporter/configuration.py
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/kebechet.py
  thoth/metrics_exporter/jobs/qeb_hwt.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#405 Remove unusued metrics
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/argo_workflows.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/kebechet.py
  thoth/metrics_exporter/jobs/qeb_hwt.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#406 Automatic update of dependency thoth-common from 0.13.8 to 0.13.9
  Pipfile.lock
Labels: bot, size/L

#407 Missing import
  openshift/buildConfig-template.yaml
  thoth/metrics_exporter/configuration.py
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/S

#409 Automatic update of dependency thoth-storages from 0.22.12 to 0.23.0
  Pipfile.lock
Labels: bot, size/M

#410 Automatic update of dependency thoth-common from 0.13.9 to 0.13.11
  Pipfile.lock
Labels: bot, size/M

#411 Automatic update of dependency prometheus-api-client from 0.2.0 to 0.3.1
  Pipfile.lock
Labels: bot, size/M

#413 Connect if the adapter is not connected
  thoth/metrics_exporter/jobs/base.py
Labels: approved, size/XS

#416 Automatic update of dependency thoth-storages from 0.23.0 to 0.23.2
  Pipfile.lock
Labels: bot, size/M

#417 Automatic update of dependency thoth-common from 0.13.11 to 0.13.12
  Pipfile.lock
Labels: bot, size/M

#420 Automatic update of dependency sentry-sdk from 0.14.4 to 0.15.1
  Pipfile.lock
Labels: bot, size/M

#421 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/XS

#414 Remove ceph
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/analysis.py
  thoth/metrics_exporter/jobs/dependency_monkey.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/package_analysis.py
  thoth/metrics_exporter/jobs/provenance.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/metrics.py
Labels: size/L

#428 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: bot, size/L

#427 Automatic update of dependency thoth-storages from 0.23.2 to 0.24.0
  Pipfile.lock
Labels: bot, size/L
