Repository thoth-station/metrics-exporter, pull requests merged in 2020-07, with the labels that each got.

#430 Remove templates handled by thoth-application
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#431 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/S

#432 Automatic update of dependency thoth-common from 0.13.13 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/S

#434 Automatic update of dependency sentry-sdk from 0.15.1 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/S

#436 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#437 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/L

#438 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#439 Automatic update of dependency sentry-sdk from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/L
