Repository thoth-station/metrics-exporter, pull requests merged in 2020-05, with the labels that each got.

#375 Release of version 0.8.2
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: bot, size/XS

#382 use count method for Ceph documents
  thoth/metrics_exporter/jobs/ceph.py
Labels: approved, size/XS

#384 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/M

#385 Automatic update of dependency sentry-sdk from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot, size/M

#386 Add metrics from Pypi
  Pipfile
  Pipfile.lock
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/pypi.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#388 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/L

#389 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/S

#390 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#391 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#392 Automatic update of dependency prometheus-client from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/S

#396 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/S

#395 Added kebechet metric and readme
  .env.template
  README.md
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/kebechet.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#397 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/M

#398 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/S
