Repository thoth-station/metrics-exporter, pull requests merged in 2020-04, with the labels that each got.

#351 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/M

#352 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/S

#354 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#355 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/L

#356 Automatic update of dependency thoth-common from 0.12.7 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#357 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/L

#358 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#359 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/XS

#360 Correct-info
  openshift/deployment-template.yaml
Labels: approved, size/XS

#361 updates the GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/M

#362 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/S

#364 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot

#365 added a service_version
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/metrics.py
  wsgi.py
Labels: enhancement, size/S

#368 Release of version 0.8.1
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: bot, size/L

#371 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: approved, bot, size/M

#373 Add argo workflows class of metrics
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/argo_workflows.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/openshift.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/utils.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L
