Repository thoth-station/metrics-exporter, pull requests merged in 2020-02, with the labels that each got.

#303 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/S

#304 Metrics for imagestreams
  thoth/metrics_exporter/jobs/openshift.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#305 Correct variables
  thoth/metrics_exporter/jobs/openshift.py
Labels: approved, size/XS

#306 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/M

#307 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#309 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#310 Qeb-Hwt App SLI
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#311 Use same time in evaluation of LSI
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#315 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/S

#314 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#312 Qeb-Hwt SLI for quality
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/common.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#313 Inspection quality sli
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#308 Metric for bloat data for the database
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#316 Reduce logs
  thoth/metrics_exporter/jobs/openshift.py
Labels: approved, size/XS

#317 Less less logs
  thoth/metrics_exporter/jobs/openshift.py
Labels: approved, size/XS

#318 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/S

#319 Reduce bucket size for GitHub App workflows
  thoth/metrics_exporter/metrics.py
Labels: approved, size/XS

#320 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#321 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/XS

#322 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#323 Use float for timestamps
  thoth/metrics_exporter/jobs/db.py
Labels: approved, size/XS

#326 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/L

#329 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot, size/S

#330 Automatic update of dependency sentry-sdk from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot, size/S

#333 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S

#335 Adjust/add some metrics
  thoth/metrics_exporter/jobs/common.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#336 Monitor workflows in pending state
  thoth/metrics_exporter/jobs/common.py
Labels: approved, size/XS

#338 Automatic update of dependency decorator from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot, size/S

#337 Wrong namespace to be monitored for solver workflows metric
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS
