Repository thoth-station/metrics-exporter, pull requests merged in 2020-01, with the labels that each got.

#258 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/L

#259 New Thoth SLI
  openshift/deployment-template.yaml
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/common.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#260 Better describe env variables
  openshift/deployment-template.yaml
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/S

#261 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#262 Happy new year!
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/base.py
  thoth/metrics_exporter/jobs/ceph.py
  thoth/metrics_exporter/jobs/common.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/openshift.py
  thoth/metrics_exporter/jobs/package_analyzer.py
  thoth/metrics_exporter/jobs/pi.py
  thoth/metrics_exporter/jobs/python.py
  thoth/metrics_exporter/jobs/software_environment.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
  thoth/metrics_exporter/metrics.py
  wsgi.py
Labels: approved, size/M

#263 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: bot, size/XS

#264 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: bot, size/S

#265 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#266 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#267 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.6
  Pipfile.lock
Labels: bot, size/L

#268 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/L

#269 Automatic update of dependency sentry-sdk from 0.13.5 to 0.14.0
  Pipfile.lock
Labels: bot, size/M

#270 Add build-analyzers to OpenShift metrics
  thoth/metrics_exporter/jobs/openshift.py
Labels: approved, size/XS

#272 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#274 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/XS

#275 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/XS

#276 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/M

#277 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/S

#278 Reduce complexity of workflow duration
  thoth/metrics_exporter/jobs/common.py
Labels: approved, size/M

#279 Fix typos
  thoth/metrics_exporter/jobs/common.py
Labels: approved, size/S

#280 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/M

#281 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/S

#282 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/XS

#283 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/S

#284 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#285 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/S

#286 Automatic update of dependency thoth-common from 0.9.26 to 0.9.28
  Pipfile.lock
Labels: bot, size/M

#291 Automatic update of dependency thoth-storages from 0.21.7 to 0.21.8
  Pipfile.lock
Labels: bot, size/M

#292 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#293 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/XS

#290 Adjust metrics for PI
  thoth/metrics_exporter/jobs/pi.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#296 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#297 Automatic update of dependency sentry-sdk from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot, size/XS

#298 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#299 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/S

#300 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/S

#301 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#302 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/L
