Repository thoth-station/metrics-exporter, pull requests merged in 2020-09, with the labels that each got.

#487 Automatic update of dependency thoth-common from 0.17.0 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/S

#488 Automatic update of dependency sentry-sdk from 0.17.1 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/S

#489 Add maintainer
  .thoth.yaml
Labels: approved, size/XS

#491 Release of version 0.8.7
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/S

#492 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.7
  Pipfile.lock
Labels: approved, bot, size/L

#493 Automatic update of dependency thoth-common from 0.17.2 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/L

#494 Automatic update of dependency sentry-sdk from 0.17.2 to 0.17.4
  Pipfile.lock
Labels: approved, bot, size/L

#495 Automatic update of dependency prometheus-api-client from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: approved, bot, size/L

#496 Add SI metrics
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/base.py
  thoth/metrics_exporter/jobs/ceph.py
  thoth/metrics_exporter/jobs/security.py
  thoth/metrics_exporter/metrics.py
Labels: approved, do-not-merge/hold, size/L

#497 Automatic update of dependency thoth-common from 0.18.1 to 0.18.2
  Pipfile.lock
Labels: approved, bot, size/S

#499 Bump version for release with new SI metrics
  Pipfile.lock
Labels: approved, size/L

#501 Release of version 0.8.8
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/S

#503 Rename metric
  thoth/metrics_exporter/jobs/security.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#508 Release of version 0.8.9
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/XS

#509 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/L

#512 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.9
  Pipfile.lock
Labels: approved, bot

#511 Introduce metrics for Thoth integrations
  Pipfile.lock
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/metrics.py
Labels: approved

#514 Automatic update of dependency sentry-sdk from 0.17.5 to 0.17.6
  Pipfile.lock
Labels: approved, bot

#515 Release of version 0.8.10
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot

#517 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.11
  Pipfile.lock
Labels: approved, bot

#520 Release of version 0.8.11
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/XS

#521 metrics-exporter runs in infra now
  .env.template
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/security.py
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#524 Automatic update of dependency sentry-sdk from 0.17.6 to 0.17.7
  Pipfile.lock
Labels: approved, bot, size/S

#525 Release of version 0.8.12
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot

#526 Adjust metrics to start with Thoth
  thoth/metrics_exporter/metrics.py
Labels: approved, size/XS

#528 Release of version 0.8.13
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/XS

#530 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#531 Automatic update of dependency sentry-sdk from 0.17.7 to 0.17.8
  Pipfile.lock
Labels: approved, bot, size/L

#533 Introduce metric for alarm on storages version in management-API
  Pipfile
  Pipfile.lock
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#535 Release of version 0.8.14
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/S
