Repository thoth-station/metrics-exporter, pull requests merged in 2020-08, with the labels that each got.

#442 Automatic update of dependency thoth-storages from 0.24.4 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/L

#443 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/L

#445 Automatic update of dependency sentry-sdk from 0.16.1 to 0.16.3
  Pipfile.lock
Labels: approved, bot, size/L

#448 Automatic update of dependency prometheus-api-client from 0.3.1 to 0.4.0
  Pipfile.lock
Labels: approved, bot, size/L

#452 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.1
  Pipfile.lock
Labels: approved, bot, size/S

#453 Automatic update of dependency sentry-sdk from 0.16.3 to 0.16.5
  Pipfile.lock
Labels: approved, bot

#455 Add check
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#457 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#459 Release of version 0.8.4
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot

#462 Automatic update of dependency thoth-storages from 0.25.1 to 0.25.2
  Pipfile.lock
Labels: approved, bot, size/S

#463 Correct errors
  thoth/metrics_exporter/jobs/python.py
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#466 Release of version 0.8.5
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/XS

#469 update module based upon storages and common functions
  pyproject.toml
  thoth/metrics_exporter/jobs/python.py
  thoth/metrics_exporter/jobs/solver.py
Labels: approved, size/XS

#470 Remove package analysis metrics
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/package_analysis.py
Labels: approved, size/M

#471 Update README
  README.md
Labels: approved, size/M

#473 Release of version 0.8.6
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/XS

#477 Automatic update of dependency thoth-storages from 0.25.3 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/S

#478 Automatic update of dependency sentry-sdk from 0.16.5 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/S

#482 Automatic update of dependency thoth-common from 0.16.1 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/S

#483 Automatic update of dependency flask-cors from 3.0.8 to 3.0.9
  Pipfile.lock
Labels: approved, bot, size/S

#484 Automatic update of dependency sentry-sdk from 0.17.0 to 0.17.1
  Pipfile.lock
Labels: approved, bot, size/S
