Repository thoth-station/metrics-exporter, pull requests merged in 2020-10, with the labels that each got.

#538 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/L

#540 Introduce metric on SI Python packages not analyzable
  thoth/metrics_exporter/jobs/security.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#542 Release of version 0.8.15
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/XS

#543 Adjust datatype
  thoth/metrics_exporter/jobs/db.py
Labels: approved, size/S

#545 Release of version 0.8.16
  CHANGELOG.md
  thoth/metrics_exporter/__init__.py
Labels: approved, bot, size/XS
