Repository thoth-station/metrics-exporter, pull requests merged in 2021-06, with the labels that each got.

#701 Update base image
  .aicoe-ci.yaml
Labels: approved, size/XS

#700 Add CVE metric
  thoth/metrics_exporter/jobs/security.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#696 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, bot, size/XS

#707 Remove long running metric
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#719 missin definition of metric
  thoth/metrics_exporter/metrics.py
Labels: approved, lgtm, size/XS

#730 Add missing labels
  thoth/metrics_exporter/jobs/db.py
Labels: approved, lgtm, size/XS
