Repository thoth-station/metrics-exporter, pull requests merged in 2021-03, with the labels that each got.

#622 Add almebic rows table metric
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#617 Introduce a metric for obtaining the current database size
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/XS

#628 formatting updates
  .pre-commit-config.yaml
  .prow.yaml
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/user.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#631 Solve type checking
  thoth/metrics_exporter/jobs/base.py
Labels: approved, size/XS

#638 Check initial connections and add Kafka metrics
  Pipfile
  Pipfile.lock
  README.md
  thoth/metrics_exporter/__init__.py
  thoth/metrics_exporter/jobs/__init__.py
  thoth/metrics_exporter/jobs/base.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/kafka.py
  thoth/metrics_exporter/jobs/security.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/metrics.py
Labels: size/L
