Repository thoth-station/metrics-exporter, pull requests merged in 2021-01, with the labels that each got.

#554 Introduce metrics for unique usage of adviser integrations
  Pipfile.lock
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/L

#547 add job to check for db corruption
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/S

#575 remove-metric
  OWNERS
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M

#576 Adjust pre commit
  .env.template
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/new_deployment.md
  .github/PULL_REQUEST_TEMPLATE.md
  Pipfile
  Pipfile.lock
  README.md
  thoth/metrics_exporter/jobs/adviser.py
  thoth/metrics_exporter/jobs/base.py
  thoth/metrics_exporter/jobs/ceph.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/jobs/inspection.py
  thoth/metrics_exporter/jobs/kebechet.py
  thoth/metrics_exporter/jobs/openshift.py
  thoth/metrics_exporter/jobs/pi.py
  thoth/metrics_exporter/jobs/security.py
  thoth/metrics_exporter/jobs/solver.py
  thoth/metrics_exporter/jobs/utils.py
  thoth/metrics_exporter/metrics.py
  wsgi.py
Labels: approved, size/L

#577 Introduce database revision metric checks
  Pipfile.lock
  thoth/metrics_exporter/configuration.py
  thoth/metrics_exporter/jobs/db.py
  thoth/metrics_exporter/metrics.py
Labels: approved, size/M
