Repository thoth-station/metrics-exporter, pull requests merged in 2021-05, with the labels that each got.

#664 Set a different values for errors, not -1
  thoth/metrics_exporter/jobs/db.py
Labels: approved, lgtm, size/XS

#667 Use convention for alarms
  thoth/metrics_exporter/jobs/ceph.py
  thoth/metrics_exporter/jobs/kafka.py
  thoth/metrics_exporter/metrics.py
Labels: approved, lgtm, size/S

#671 update the prow resource limits
  .prow.yaml
  .thoth.yaml
Labels: approved, size/XS
