Repository thoth-station/metrics-exporter, pull requests merged in 2022-07, with the labels that each got.

#858 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test

#857 Fix .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: size/XS, lgtm

#860 Update OWNERS
  OWNERS
Labels: size/S, lgtm
