Repository thoth-station/metrics-exporter, pull requests merged in 2022-01, with the labels that each got.

#807 introduce metrics for software stacks maintained by Kebechet
  thoth/metrics_exporter/jobs/kebechet.py
  thoth/metrics_exporter/metrics.py
Labels: size/S, approved

#810 Add container info in README
  README.md
Labels: size/S, approved

#814 Remove unused playbooks
  playbooks/provision.yaml
Labels: size/S, approved

#817 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS

#819 Remove unused .thothTemplate.yaml
  .thothTemplate.yaml
Labels: size/S, approved

#815 Remove development dependencies
  Pipfile
  Pipfile.lock
Labels: approved, size/XL
